### ISSUE TITLE
error in processing 2023 data

### ISSUE THREAD

**Issue by mbjones** [howweirdistheweather/weather_app#10]
All years from 1950-2022 processed without error over the last few days. When I updated 2023 and ran tiletool, I now get an error for 2023 saying an attribute is missing. Logs below.

```
** HWITW data processing tool v0.9.6 **

debug: start_week 38 num_weeks 39 total_num_hours 6703
Output hwglobal-temperature_and_humidity-2023.nc
Traceback (most recent call last):
  File "/cdstotile/tiletool.py", line 617, in <module>
    main()
  File "/cdstotile/tiletool.py", line 605, in main
    load_netcdfs( flag_args, input_path, output_path, start_year, end_year )
  File "/cdstotile/tiletool.py", line 413, in load_netcdfs
    process_data_group( flag_args, inp_path, out_path, dir_name, year, dg_name, dg );
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cdstotile/tiletool.py", line 310, in process_data_group
    wk_var.append(week_i + 1)
    ^^^^^^^^^^^^^
  File "src/netCDF4/_netCDF4.pyx", line 4909, in netCDF4._netCDF4.Variable.__getattr__
  File "src/netCDF4/_netCDF4.pyx", line 4631, in netCDF4._netCDF4.Variable.getncattr
  File "src/netCDF4/_netCDF4.pyx", line 1545, in netCDF4._netCDF4._get_att
  File "src/netCDF4/_netCDF4.pyx", line 2029, in netCDF4._netCDF4._ensure_nc_success
AttributeError: NetCDF: Attribute not found
```

I searched for the `expver` and did not find it in any of the files.

**Comment by jamcinnes2** [comment]
Fixed in 0386f8fd2a8ce4a2bbef980381cedc4bb6b217a3.
